version: '3.9'

services:
  patients-db:
    image: postgres:15-alpine
    container_name: patients-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pacientes_db
      POSTGRES_USER: patients_user
      POSTGRES_PASSWORD: patients_pass
    ports:
      - "5434:5432"
    volumes:
      - patients_data:/var/lib/postgresql/data
      - ./docker/patients/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U patients_user -d pacientes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  patients_data:
